export enum SlotSymbol {
  LEMON = 'LEMON',
  CHERRY = 'CHERRY',
  GRAPE = 'GRAPE',
  BELL = 'BELL',
  BAR = 'BAR',
  SEVEN = 'SEVEN',
  DIAMOND = 'DIAMOND',
}

export const REEL_LENGTH = 31;

export const REELS: SlotSymbol[][] = [
  [
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.BELL,
    SlotSymbol.BELL,
    SlotSymbol.BAR,
    SlotSymbol.BAR,
    SlotSymbol.SEVEN,
    SlotSymbol.SEVEN,
    SlotSymbol.DIAMOND,
  ],
  [
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.BELL,
    SlotSymbol.BELL,
    SlotSymbol.BAR,
    SlotSymbol.BAR,
    SlotSymbol.SEVEN,
    SlotSymbol.SEVEN,
    SlotSymbol.DIAMOND,
  ],
  [
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.LEMON,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.CHERRY,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.GRAPE,
    SlotSymbol.BELL,
    SlotSymbol.BELL,
    SlotSymbol.BELL,
    SlotSymbol.BELL,
    SlotSymbol.BELL,
    SlotSymbol.BAR,
    SlotSymbol.BAR,
    SlotSymbol.BAR,
    SlotSymbol.BAR,
    SlotSymbol.SEVEN,
    SlotSymbol.SEVEN,
    SlotSymbol.SEVEN,
    SlotSymbol.DIAMOND,
    SlotSymbol.DIAMOND,
  ],
];

export const PAYTABLE_3OAK: Record<SlotSymbol, number> = {
  [SlotSymbol.LEMON]: 14,
  [SlotSymbol.CHERRY]: 16,
  [SlotSymbol.GRAPE]: 20,
  [SlotSymbol.BELL]: 30,
  [SlotSymbol.BAR]: 60,
  [SlotSymbol.SEVEN]: 100,
  [SlotSymbol.DIAMOND]: 150,
};

export const PAYTABLE_2OAK: Record<SlotSymbol, number> = {
  [SlotSymbol.LEMON]: 0.6,
  [SlotSymbol.CHERRY]: 0.8,
  [SlotSymbol.GRAPE]: 1.5,
  [SlotSymbol.BELL]: 2.5,
  [SlotSymbol.BAR]: 3,
  [SlotSymbol.SEVEN]: 6,
  [SlotSymbol.DIAMOND]: 10,
};

export const SCALING_FACTOR = 1;

export const SLOT_SESSION_TTL = 60 * 60 * 24;
