services:
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '3100:3100'
    environment:
      - PORT=3100
    volumes:
      - app_data:/app/data

volumes:
  app_data:
