services:
  app:
    image: node:lts-alpine
    stdin_open: true
    tty: true
    environment:
      - NODE_OPTIONS=--experimental-strip-types
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    ports:
      - 3000:3000
    command: sh -c "npm install && sh"
