services:
  server:
    build: ./server
    ports:
      - "3500:3500"
    environment:
      - ORIGIN=http://localhost:3000
    volumes:
      - files_data:/app/files

  client:
    build: ./client
    ports:
      - "3000:3000"

volumes:
  files_data:
