ALTER TYPE "coin_transaction_type" ADD VALUE IF NOT EXISTS 'ROULETTE_BET';
ALTER TYPE "coin_transaction_type" ADD VALUE IF NOT EXISTS 'ROULETTE_WIN';
ALTER TYPE "coin_transaction_type" ADD VALUE IF NOT EXISTS 'PURCHASED_COINS';
